#!/usr/bin/env python

import random
import pygame

from body import Brain, Eye, Hand
from Exceptions import ExitSMLBL2


class SMLBL2(object):
    """
    Bootstrap class.
    """
    def __init__(self):
        self.print_init("pygame")
        pygame.init()

        self.print_init("brain")
        self.brain  = Brain()                    # model
        self.print_init("eye")
        self.eye    = Eye(self.brain)            # view
        self.print_init("hand")
        self.hand   = Hand(self.brain, self.eye) # controller


    def print_init(self, item):
        init_words = ["Enabling", "Starting", "Initializing", "Summoning",
                      "Waking", "Assembling", "Acquaring", "Stealing",
                      "Converting"]

        random.seed()
        word = init_words[random.randint(0, len(init_words) - 1)]
        print "%s %s..." % (word, item)


    def run(self):
        running = True
        while running:
            try:
                # handle input
                self.hand.handle_input(pygame.event.poll())

                # handle game state
                self.brain.tick()

                # repaint
                self.eye.repaint()
            except ExitSMLBL2:
                running = False

        print "Exiting..."



if __name__ == "__main__":
    smlbl2 = SMLBL2()
    smlbl2.run()
