#!/usr/bin/env python

import random
import pygame

from body import Brain, Eye, Hand
from Exceptions import ExitSMLBL2


class SMLBL2(object):
    """
    Bootstrap class.
    """
    def __init__(self):
        pygame.init()

        self.brain  = Brain()                    # model
        self.eye    = Eye(self.brain)            # view
        self.hand   = Hand(self.brain, self.eye) # controller


    def run(self):
        running = True
        while running:
            try:
                # handle input
                self.hand.handle_input(pygame.event.poll())

                # handle game state
                self.brain.tick()

                # repaint
                self.eye.repaint()
            except ExitSMLBL2:
                running = False

        print "Exiting..."



if __name__ == "__main__":
    smlbl2 = SMLBL2()
    smlbl2.run()
